maxretry = 3
pollinterval = 15

[myups]
    driver = usbhid-ups
    port = auto
    vendorid = 0764
    productid = 0501
    offdelay = 120
    ondelay = 240
    pollonly
    pollfreq = 30
    desc = "CyberPower UT2200EG"
