RUN_AS_USER root
MONITOR myups@localhost 1 monuser F6nGksUfGNEhhKoxHZQPMQ primary

# Сколько UPS должны сказать "критично" для начала выключения.
# У нас 1 UPS — значит 1.
MINSUPPLIES 1

# Команда выключения
SHUTDOWNCMD "/sbin/shutdown -h now"

# Таймер: после получения сигнала ONBATT ждём 1200 секунд (20 минут),
# потом вызываем FSD (Forced Shutdown).
# Если питание вернулось раньше — таймер сбрасывается.
HOSTSYNC 15
DEADTIME 25
POWERDOWNFLAG /etc/killpower

# Интервал опроса upsmon → upsd
POLLFREQ 5
POLLFREQALERT 5

# Скрипт-обработчик событий
NOTIFYCMD /usr/sbin/upssched

# Какие события отслеживать
NOTIFYMSG ONLINE   "UPS %s: on line power"
NOTIFYMSG ONBATT   "UPS %s: on battery"
NOTIFYMSG LOWBATT  "UPS %s: battery is low"
NOTIFYMSG FSD      "UPS %s: forced shutdown in progress"
NOTIFYMSG COMMOK   "Communications with UPS %s established"
NOTIFYMSG COMMBAD  "Communications with UPS %s lost"
NOTIFYMSG SHUTDOWN "UPS %s: Auto logout and shutdown proceeding"
NOTIFYMSG REPLBATT "UPS %s: battery needs to be replaced"
NOTIFYMSG NOCOMM   "UPS %s: is unavailable"
NOTIFYMSG NOPARENT "upsmon parent process died - shutdown impossible"

NOTIFYFLAG ONLINE   SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT   SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT  SYSLOG+WALL+EXEC
NOTIFYFLAG FSD      SYSLOG+WALL+EXEC
NOTIFYFLAG COMMOK   SYSLOG+WALL+EXEC
NOTIFYFLAG COMMBAD  SYSLOG+WALL+EXEC
NOTIFYFLAG SHUTDOWN SYSLOG+WALL+EXEC
NOTIFYFLAG REPLBATT SYSLOG+WALL
NOTIFYFLAG NOCOMM   SYSLOG+WALL+EXEC
NOTIFYFLAG NOPARENT SYSLOG+WALL

RBWARNTIME 43200
NOCOMMWARNTIME 600

FINALDELAY 5
