CMDSCRIPT /etc/nut/upssched-cmd
PIPEFN /run/nut/upssched.pipe
LOCKFN /run/nut/upssched.lock

# Переход на батарею — ждём 20 минут
AT ONBATT * START-TIMER onbatt 120

# Питание вернулось — отменяем таймер
AT ONLINE * CANCEL-TIMER onbatt online

# Батарея < 40% — немедленное выключение
AT LOWBATT * EXECUTE onbatt

# Потеря связи с UPS
AT COMMBAD * START-TIMER commbad 30
AT COMMOK * CANCEL-TIMER commbad commok
AT NOCOMM * EXECUTE commbad

# Выключение
AT SHUTDOWN * EXECUTE powerdown
